version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  target-branch: dev
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.1.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
